export const DB_KEYS = {
  ACCOUNT_DB: 'ACCOUNT_DB',
  TICKET_DB: 'TICKET_DB',
  PAYMENT_DB: 'PAYMENT_DB',
  SLOT_MATRIX_DB: 'SLOT_MATRIX_DB',
  INFO_DB: 'INFO_DB',
  PRIORITY_PRICE_DB: 'PRIORITY_PRICE_DB',
  ALERT_DB: 'ALERT_DB'
};
